### ISSUE TITLE
线下环境 portal 无法访问线上环境 meta service

### ISSUE THREAD

**Issue by revolyw** [apolloconfig/apollo#5083]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug
由于 portal 部署了线下、线上两套环境，但是线下的 portal 在一部分 meta services 时会报错，而且由于健康检查的机制，虽然不影响功能，但是这个报错日志会不停地刷，影响开发调试，所以希望探讨一下如何优化，支持一下这种场景下的使用。
具体场景是：portal 部署了线下、线上两套环境，分别支持了 4 套 Envs（DEV、TEST、UAT、PRD），可以按部署逻辑分为两组：线下（DEV、TEST）、线上（UAT、PRD），线下线上对应的 meta service 不同且网络是不互通的（这是无法访问的原因）

**复现**

通过如下步骤可以复现：

1. 部署 4 个 env：DEV、TEST、UAT、PRD 的 adminservice 和 configservice，DEV、TEST 用一个 meta service、UAT、PRD 用另一个 meta service ，网络不互通
2. 部署一个 portal 和 DEV、TEST 所在环境网络互通
3. 启动 portal

**期望**

简介明了地描述你希望正常情况下应该发生什么
不产生报错异常和堆栈日志

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.8.6
- 错误日志：见截图
- 配置：无
- 平台和操作系统：ubuntu 18.04.6 LTS

**Comment by revolyw** [comment]
目前 portal 在线下线上部署时会有不同的环境参数，例如 spring.profiles.active。 
因此我目前的想法是，针对线下环境，通过环境参数在加载 env 和健康检查时屏蔽掉现在的 env（UAT、PRD）
但是这样会使原来的代码变得复杂，所以我想知道是否有更好的办法满足这种场景

**Comment by nobodyiam** [comment]
portal 线上和线下是两套环境的话，portal 数据库是一套还是两套？
如果 portal 数据库是一套，可以通过指定不同的 [apollo.portal.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8) 来让线下的 portal 只启用线下环境，线上的 portal 只启用线上环境。
如果 portal 数据库是两套，那就完全独立了，各自配置即可。

**Comment by revolyw** [comment]
> portal 线上和线下是两套环境的话，portal 数据库是一套还是两套？ 如果 portal 数据库是一套，可以通过指定不同的 [apollo.portal.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8) 来让线下的 portal 只启用线下环境，线上的 portal 只启用线上环境。 如果 portal 数据库是两套，那就完全独立了，各自配置即可。

我的 portal 数据库是一套。 通过 [apollo.portal.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8)  满足了我的场景，谢谢您的解答。

**Comment by revolyw** [comment]
> portal 线上和线下是两套环境的话，portal 数据库是一套还是两套？ 如果 portal 数据库是一套，可以通过指定不同的 [apollo.portal.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8) 来让线下的 portal 只启用线下环境，线上的 portal 只启用线上环境。 如果 portal 数据库是两套，那就完全独立了，各自配置即可。

我的 portal 数据库是一套。 通过 [apollo.portal.envs](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8)  满足了我的场景，谢谢您的解答。
